### ISSUE TITLE
Spring client with access to multiple GIT repositories 

### ISSUE THREAD

**Issue by tvijayakannan** [cloudfoundry/config-server#14]
I do have requirement to use pcf config service in one of the  spring boot cloud config client app to serve application configuration in deserved format like json. Application name will be requested dynamically to client app as part of the request. For example 

Branding application - Which is using pcf config service
/rest/v1/branding/{appName}/{environment}. 
This controlled method should retrieve configuration from GIT report based on environment and  
send as JSON response to consumers
 
Spring cloud config server is retrieving configuration based on spring.application.name and will it support multiple application names

**Comment by h4xnoodle** [comment]
@tvijayakannan is it possible you have this repo confused with Spring Cloud Config Server? 

This repo is for Bosh's idea of a contract between some credential-generating/storing service and the bosh director. Credhub is a popular implementation.

**Comment by tvijayakannan** [comment]
@h4xnoodle yes i am confused with Spring cloud config server.. i was checking that code and thought open it over there but somehow it's landed here. closing it now. Thanks for your comments
