### ISSUE TITLE
Intermediate certificates generated by config-server will have an incorrect CA.

### ISSUE THREAD

**Issue by andrew-su** [cloudfoundry/config-server#5]
When generating an intermediate CA, the response body contains incorrect values.

Expected:
```
{
  "id": "some_id",
  "name":"my_cert",
  "value": {
    "ca" : "Root/Parent CA",
    "certificate": "Intermediate CA",
    "private_key": "Intermediate CA Private Key"
  }
}
```

Actual:
```
{
  "id": "some_id",
  "name":"my_cert",
  "value": {
    "ca" : "Intermediate CA",
    "certificate": "Intermediate CA",
    "private_key": "Intermediate CA Private Key"
  }
}
```
It looks like the problem lies here:
https://github.com/cloudfoundry/config-server/blob/2d6f3ab66c92c437fae71a077c5bc6992466b35b/types/certificate_generator.go#L101
where it doesn't differentiate between intermediate and regular CA.

The certificates are signed correctly, it's only the response containing the wrong certificate for the `ca` field.

**Comment by pivotal-jamil-shamy** [comment]
Fixed in [#151338592](https://www.pivotaltracker.com/story/show/151338592)
 
Should be included in BOSH CLI version [5.3.1](https://github.com/cloudfoundry/bosh-cli/releases/tag/v5.3.1)
